### ISSUE TITLE
Not working in Arduino ide 

### ISSUE THREAD

**Issue by theeOneonly** [cdmsoftware/ArduinoDuckyScript#3]
I have downloaded the newest ide for Arduino on Mac and it has not worked it just give me a error for a weird reason I'm new to arduino and need help. I'm trying to make a bad usb with my Arduino pro micro. the error is like "error Keyboard no such file or dir". this happens when the code use Keyboard.press etc. this is for the admin file

**Comment by christofersimbar** [comment]
I never use Mac when compiling the sketch file. Make sure you select a board that support keyboard emulation in Tools > Board

**Comment by SabyasachiRana** [comment]
What's the password ?? in  add admin script?

**Comment by christofersimbar** [comment]
> What's the password ?? in add admin script?

123456

**Comment by theeOneonly** [comment]
how would you install this on your pro micro using the library HID?

**Comment by SabyasachiRana** [comment]
I'm using Arduino Leonardo..Which is act like a HID device... without any library..

**Comment by theeOneonly** [comment]
how do you install this script on the leonardo

**Comment by SabyasachiRana** [comment]
just copy the code and paste.. complete, Nothing Extra

**Comment by theeOneonly** [comment]
thanks

**Comment by arkanme** [comment]
Trimis din Yahoo Mail pe Android

**Comment by arkanme** [comment]
Vhh

Trimis din Yahoo Mail pe Android

**Comment by arkanme** [comment]
ffhjjdd

Trimis din Yahoo Mail pe Android

**Comment by arkanme** [comment]
Cgksfk

Trimis din Yahoo Mail pe Android
